// @ts-nocheck
// eslint-disable
// ---------------------------------------------------
// 🚗🚦 Generated by nuxt-typed-router. Do not modify !
// ---------------------------------------------------

export type RoutePathSchema =
  | '/'
  | '/auth/rul'
  | '/chats/'
  | '/employees/'
  | '/my-auction'
  | '/my-products/'
  | '/my-products/add_products/realTime-:storeId'
  | '/my-products/add_products/virtual'
  | '/my-products/add_store'
  | '/my-products/edit_product/realTime-:productId'
  | '/my-products/edit_product/virtual-:productId'
  | '/my-products/orders-and-payment-page/index-:storeId'
  | '/my-products/orders-and-payment-page/index-:storeId/delivery-:storeId'
  | '/my-products/orders-and-payment-page/index-:storeId/self-:storeId'
  | '/my-products/edit_store-:storeId'
  | '/my-products/realTime-:storeId'
  | '/my-products/virtual'
  | '/my-products/order_per_store-:storeid'
  | '/my-products/orders-and-payment'
  | '/my-products/special-discount'
  | '/my-services/'
  | '/my-services/add/realtime'
  | '/my-services/add/virtual'
  | '/my-services/edit/realtime-:service_id'
  | '/my-services/edit/virtual-:service_id'
  | '/my-services/virtual'
  | '/my-services/orders-and-payment'
  | '/review'
  | '/settings'
  | '/store-employee/account'
  | '/store-employee'
  | '/store-employee/chats/'
  | '/store-employee/order-page/index-:storeId/delivery-:storeId'
  | '/store-employee/order-page/index-:storeId/self-:storeId'
  | '/store-employee/add-product-:storeId'
  | '/store-employee/discount'
  | '/store-employee/order-page/index-:storeId'
  | '/store-employee/edit-product-:productId'
  | '/store-employee/products-:storeId'
  | '/store-employee/store';

type ValidStringPath<T> = T extends `${string} ${string}` ? false : T extends '' ? false : true;

type ValidParam<T, R extends boolean = true> = T extends `${infer A}/${infer B}`
  ? A extends `${string} ${string}`
    ? false
    : A extends `?${string}`
      ? false
      : A extends `${string} ${string}`
        ? false
        : A extends ''
          ? B extends ''
            ? true
            : false
          : B extends `?${string}`
            ? false
            : B extends `#${string}`
              ? true
              : B extends ''
                ? true
                : false
  : R extends true
    ? T extends ''
      ? false
      : ValidParam<T, false>
    : T extends `?${string}`
      ? false
      : T extends `${string} ${string}`
        ? false
        : true;

type ValidEndOfPath<T> = T extends `/`
  ? true
  : T extends ''
    ? true
    : T extends `${string} ${string}`
      ? false
      : T extends `?${string}`
        ? true
        : T extends `#${string}`
          ? true
          : false;

type ValidateAuthRul<T> = T extends `/auth/rul${infer TRul}`
  ? ValidEndOfPath<TRul> extends false
    ? "End of path '/auth/rul' is invalid"
    : true
  : false;

type ValidateChats<T> = T extends `/chats${infer TChats}`
  ? ValidEndOfPath<TChats> extends false
    ? "End of path '/chats/' is invalid"
    : true
  : false;

type ValidateEmployees<T> = T extends `/employees${infer TEmployees}`
  ? ValidEndOfPath<TEmployees> extends false
    ? "End of path '/employees/' is invalid"
    : true
  : false;

type ValidateMyAuction<T> = T extends `/my-auction${infer TMyAuction}`
  ? ValidEndOfPath<TMyAuction> extends false
    ? "End of path '/my-auction' is invalid"
    : true
  : false;

type ValidateMyProducts<T> = T extends `/my-products${infer TMyProducts}`
  ? ValidEndOfPath<TMyProducts> extends false
    ? "End of path '/my-products/' is invalid"
    : true
  : false;

type ValidateMyProductsAddProductsRealTimeStoreId<T> =
  T extends `/my-products/add_products/realTime-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/my-products/add_products/realTime-:storeId' is invalid"
      : true
    : false;

type ValidateMyProductsAddProductsVirtual<T> =
  T extends `/my-products/add_products/virtual${infer TVirtual}`
    ? ValidEndOfPath<TVirtual> extends false
      ? "End of path '/my-products/add_products/virtual' is invalid"
      : true
    : false;

type ValidateMyProductsAddStore<T> = T extends `/my-products/add_store${infer TAddStore}`
  ? ValidEndOfPath<TAddStore> extends false
    ? "End of path '/my-products/add_store' is invalid"
    : true
  : false;

type ValidateMyProductsEditProductRealTimeProductId<T> =
  T extends `/my-products/edit_product/realTime-${infer TProductId}`
    ? ValidParam<TProductId> extends false
      ? "Parameter {productId} of path '/my-products/edit_product/realTime-:productId' is invalid"
      : true
    : false;

type ValidateMyProductsEditProductVirtualProductId<T> =
  T extends `/my-products/edit_product/virtual-${infer TProductId}`
    ? ValidParam<TProductId> extends false
      ? "Parameter {productId} of path '/my-products/edit_product/virtual-:productId' is invalid"
      : true
    : false;

type ValidateMyProductsOrdersAndPaymentPageIndexStoreId<T> =
  T extends `/my-products/orders-and-payment-page/index-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/my-products/orders-and-payment-page/index-:storeId' is invalid"
      : true
    : false;

type ValidateMyProductsOrdersAndPaymentPageIndexStoreIdDeliveryStoreId<T> =
  T extends `/my-products/orders-and-payment-page/index-${infer TStoreId}/delivery-${infer TStoreId}`
    ? ValidStringPath<TStoreId> extends false
      ? "Parameter {storeId} of path '/my-products/orders-and-payment-page/index-:storeId/delivery-:storeId' is required"
      : ValidParam<TStoreId> extends false
        ? "Parameter {storeId} of path '/my-products/orders-and-payment-page/index-:storeId/delivery-:storeId' is invalid"
        : true
    : false;

type ValidateMyProductsOrdersAndPaymentPageIndexStoreIdSelfStoreId<T> =
  T extends `/my-products/orders-and-payment-page/index-${infer TStoreId}/self-${infer TStoreId}`
    ? ValidStringPath<TStoreId> extends false
      ? "Parameter {storeId} of path '/my-products/orders-and-payment-page/index-:storeId/self-:storeId' is required"
      : ValidParam<TStoreId> extends false
        ? "Parameter {storeId} of path '/my-products/orders-and-payment-page/index-:storeId/self-:storeId' is invalid"
        : true
    : false;

type ValidateMyProductsEditStoreStoreId<T> = T extends `/my-products/edit_store-${infer TStoreId}`
  ? ValidParam<TStoreId> extends false
    ? "Parameter {storeId} of path '/my-products/edit_store-:storeId' is invalid"
    : true
  : false;

type ValidateMyProductsRealTimeStoreId<T> = T extends `/my-products/realTime-${infer TStoreId}`
  ? ValidParam<TStoreId> extends false
    ? "Parameter {storeId} of path '/my-products/realTime-:storeId' is invalid"
    : true
  : false;

type ValidateMyProductsVirtual<T> = T extends `/my-products/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/my-products/virtual' is invalid"
    : true
  : false;

type ValidateMyProductsOrderPerStoreStoreid<T> =
  T extends `/my-products/order_per_store-${infer TStoreid}`
    ? ValidParam<TStoreid> extends false
      ? "Parameter {storeid} of path '/my-products/order_per_store-:storeid' is invalid"
      : true
    : false;

type ValidateMyProductsOrdersAndPayment<T> =
  T extends `/my-products/orders-and-payment${infer TOrdersAndPayment}`
    ? ValidEndOfPath<TOrdersAndPayment> extends false
      ? "End of path '/my-products/orders-and-payment' is invalid"
      : true
    : false;

type ValidateMyProductsSpecialDiscount<T> =
  T extends `/my-products/special-discount${infer TSpecialDiscount}`
    ? ValidEndOfPath<TSpecialDiscount> extends false
      ? "End of path '/my-products/special-discount' is invalid"
      : true
    : false;

type ValidateMyServices<T> = T extends `/my-services${infer TMyServices}`
  ? ValidEndOfPath<TMyServices> extends false
    ? "End of path '/my-services/' is invalid"
    : true
  : false;

type ValidateMyServicesAddRealtime<T> = T extends `/my-services/add/realtime${infer TRealtime}`
  ? ValidEndOfPath<TRealtime> extends false
    ? "End of path '/my-services/add/realtime' is invalid"
    : true
  : false;

type ValidateMyServicesAddVirtual<T> = T extends `/my-services/add/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/my-services/add/virtual' is invalid"
    : true
  : false;

type ValidateMyServicesEditRealtimeServiceId<T> =
  T extends `/my-services/edit/realtime-${infer TServiceId}`
    ? ValidParam<TServiceId> extends false
      ? "Parameter {service_id} of path '/my-services/edit/realtime-:service_id' is invalid"
      : true
    : false;

type ValidateMyServicesEditVirtualServiceId<T> =
  T extends `/my-services/edit/virtual-${infer TServiceId}`
    ? ValidParam<TServiceId> extends false
      ? "Parameter {service_id} of path '/my-services/edit/virtual-:service_id' is invalid"
      : true
    : false;

type ValidateMyServicesVirtual<T> = T extends `/my-services/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/my-services/virtual' is invalid"
    : true
  : false;

type ValidateMyServicesOrdersAndPayment<T> =
  T extends `/my-services/orders-and-payment${infer TOrdersAndPayment}`
    ? ValidEndOfPath<TOrdersAndPayment> extends false
      ? "End of path '/my-services/orders-and-payment' is invalid"
      : true
    : false;

type ValidateReview<T> = T extends `/review${infer TReview}`
  ? ValidEndOfPath<TReview> extends false
    ? "End of path '/review' is invalid"
    : true
  : false;

type ValidateSettings<T> = T extends `/settings${infer TSettings}`
  ? ValidEndOfPath<TSettings> extends false
    ? "End of path '/settings' is invalid"
    : true
  : false;

type ValidateStoreEmployeeAccount<T> = T extends `/store-employee/account${infer TAccount}`
  ? ValidEndOfPath<TAccount> extends false
    ? "End of path '/store-employee/account' is invalid"
    : true
  : false;

type ValidateStoreEmployee<T> = T extends `/store-employee${infer TStoreEmployee}`
  ? ValidEndOfPath<TStoreEmployee> extends false
    ? "End of path '/store-employee' is invalid"
    : true
  : false;

type ValidateStoreEmployeeChats<T> = T extends `/store-employee/chats${infer TChats}`
  ? ValidEndOfPath<TChats> extends false
    ? "End of path '/store-employee/chats/' is invalid"
    : true
  : false;

type ValidateStoreEmployeeOrderPageIndexStoreIdDeliveryStoreId<T> =
  T extends `/store-employee/order-page/index-${infer TStoreId}/delivery-${infer TStoreId}`
    ? ValidStringPath<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/order-page/index-:storeId/delivery-:storeId' is required"
      : ValidParam<TStoreId> extends false
        ? "Parameter {storeId} of path '/store-employee/order-page/index-:storeId/delivery-:storeId' is invalid"
        : true
    : false;

type ValidateStoreEmployeeOrderPageIndexStoreIdSelfStoreId<T> =
  T extends `/store-employee/order-page/index-${infer TStoreId}/self-${infer TStoreId}`
    ? ValidStringPath<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/order-page/index-:storeId/self-:storeId' is required"
      : ValidParam<TStoreId> extends false
        ? "Parameter {storeId} of path '/store-employee/order-page/index-:storeId/self-:storeId' is invalid"
        : true
    : false;

type ValidateStoreEmployeeAddProductStoreId<T> =
  T extends `/store-employee/add-product-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/add-product-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeDiscount<T> = T extends `/store-employee/discount${infer TDiscount}`
  ? ValidEndOfPath<TDiscount> extends false
    ? "End of path '/store-employee/discount' is invalid"
    : true
  : false;

type ValidateStoreEmployeeOrderPageIndexStoreId<T> =
  T extends `/store-employee/order-page/index-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/order-page/index-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeEditProductProductId<T> =
  T extends `/store-employee/edit-product-${infer TProductId}`
    ? ValidParam<TProductId> extends false
      ? "Parameter {productId} of path '/store-employee/edit-product-:productId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeProductsStoreId<T> =
  T extends `/store-employee/products-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/products-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeStore<T> = T extends `/store-employee/store${infer TStore}`
  ? ValidEndOfPath<TStore> extends false
    ? "End of path '/store-employee/store' is invalid"
    : true
  : false;

export type ValidatePath<T extends string> = T extends string
  ? T extends '/'
    ? T
    : ValidateAuthRul<T> extends true
      ? T
      : ValidateChats<T> extends true
        ? T
        : ValidateEmployees<T> extends true
          ? T
          : ValidateMyAuction<T> extends true
            ? T
            : ValidateMyProducts<T> extends true
              ? T
              : ValidateMyProductsAddProductsRealTimeStoreId<T> extends true
                ? T
                : ValidateMyProductsAddProductsVirtual<T> extends true
                  ? T
                  : ValidateMyProductsAddStore<T> extends true
                    ? T
                    : ValidateMyProductsEditProductRealTimeProductId<T> extends true
                      ? T
                      : ValidateMyProductsEditProductVirtualProductId<T> extends true
                        ? T
                        : ValidateMyProductsOrdersAndPaymentPageIndexStoreId<T> extends true
                          ? T
                          : ValidateMyProductsOrdersAndPaymentPageIndexStoreIdDeliveryStoreId<T> extends true
                            ? T
                            : ValidateMyProductsOrdersAndPaymentPageIndexStoreIdSelfStoreId<T> extends true
                              ? T
                              : ValidateMyProductsEditStoreStoreId<T> extends true
                                ? T
                                : ValidateMyProductsRealTimeStoreId<T> extends true
                                  ? T
                                  : ValidateMyProductsVirtual<T> extends true
                                    ? T
                                    : ValidateMyProductsOrderPerStoreStoreid<T> extends true
                                      ? T
                                      : ValidateMyProductsOrdersAndPayment<T> extends true
                                        ? T
                                        : ValidateMyProductsSpecialDiscount<T> extends true
                                          ? T
                                          : ValidateMyServices<T> extends true
                                            ? T
                                            : ValidateMyServicesAddRealtime<T> extends true
                                              ? T
                                              : ValidateMyServicesAddVirtual<T> extends true
                                                ? T
                                                : ValidateMyServicesEditRealtimeServiceId<T> extends true
                                                  ? T
                                                  : ValidateMyServicesEditVirtualServiceId<T> extends true
                                                    ? T
                                                    : ValidateMyServicesVirtual<T> extends true
                                                      ? T
                                                      : ValidateMyServicesOrdersAndPayment<T> extends true
                                                        ? T
                                                        : ValidateReview<T> extends true
                                                          ? T
                                                          : ValidateSettings<T> extends true
                                                            ? T
                                                            : ValidateStoreEmployeeAccount<T> extends true
                                                              ? T
                                                              : ValidateStoreEmployee<T> extends true
                                                                ? T
                                                                : ValidateStoreEmployeeChats<T> extends true
                                                                  ? T
                                                                  : ValidateStoreEmployeeOrderPageIndexStoreIdDeliveryStoreId<T> extends true
                                                                    ? T
                                                                    : ValidateStoreEmployeeOrderPageIndexStoreIdSelfStoreId<T> extends true
                                                                      ? T
                                                                      : ValidateStoreEmployeeAddProductStoreId<T> extends true
                                                                        ? T
                                                                        : ValidateStoreEmployeeDiscount<T> extends true
                                                                          ? T
                                                                          : ValidateStoreEmployeeOrderPageIndexStoreId<T> extends true
                                                                            ? T
                                                                            : ValidateStoreEmployeeEditProductProductId<T> extends true
                                                                              ? T
                                                                              : ValidateStoreEmployeeProductsStoreId<T> extends true
                                                                                ? T
                                                                                : ValidateStoreEmployeeStore<T> extends true
                                                                                  ? T
                                                                                  : string extends T
                                                                                    ? T
                                                                                    : `Error: ${
                                                                                        | ValidateAuthRul<T>
                                                                                        | ValidateChats<T>
                                                                                        | ValidateEmployees<T>
                                                                                        | ValidateMyAuction<T>
                                                                                        | ValidateMyProducts<T>
                                                                                        | ValidateMyProductsAddProductsRealTimeStoreId<T>
                                                                                        | ValidateMyProductsAddProductsVirtual<T>
                                                                                        | ValidateMyProductsAddStore<T>
                                                                                        | ValidateMyProductsEditProductRealTimeProductId<T>
                                                                                        | ValidateMyProductsEditProductVirtualProductId<T>
                                                                                        | ValidateMyProductsOrdersAndPaymentPageIndexStoreId<T>
                                                                                        | ValidateMyProductsOrdersAndPaymentPageIndexStoreIdDeliveryStoreId<T>
                                                                                        | ValidateMyProductsOrdersAndPaymentPageIndexStoreIdSelfStoreId<T>
                                                                                        | ValidateMyProductsEditStoreStoreId<T>
                                                                                        | ValidateMyProductsRealTimeStoreId<T>
                                                                                        | ValidateMyProductsVirtual<T>
                                                                                        | ValidateMyProductsOrderPerStoreStoreid<T>
                                                                                        | ValidateMyProductsOrdersAndPayment<T>
                                                                                        | ValidateMyProductsSpecialDiscount<T>
                                                                                        | ValidateMyServices<T>
                                                                                        | ValidateMyServicesAddRealtime<T>
                                                                                        | ValidateMyServicesAddVirtual<T>
                                                                                        | ValidateMyServicesEditRealtimeServiceId<T>
                                                                                        | ValidateMyServicesEditVirtualServiceId<T>
                                                                                        | ValidateMyServicesVirtual<T>
                                                                                        | ValidateMyServicesOrdersAndPayment<T>
                                                                                        | ValidateReview<T>
                                                                                        | ValidateSettings<T>
                                                                                        | ValidateStoreEmployeeAccount<T>
                                                                                        | ValidateStoreEmployee<T>
                                                                                        | ValidateStoreEmployeeChats<T>
                                                                                        | ValidateStoreEmployeeOrderPageIndexStoreIdDeliveryStoreId<T>
                                                                                        | ValidateStoreEmployeeOrderPageIndexStoreIdSelfStoreId<T>
                                                                                        | ValidateStoreEmployeeAddProductStoreId<T>
                                                                                        | ValidateStoreEmployeeDiscount<T>
                                                                                        | ValidateStoreEmployeeOrderPageIndexStoreId<T>
                                                                                        | ValidateStoreEmployeeEditProductProductId<T>
                                                                                        | ValidateStoreEmployeeProductsStoreId<T>
                                                                                        | ValidateStoreEmployeeStore<T>}`
  : never;

// RouteNameFromPath, RouteNameFromLocalePath
export type RouteNameFromPath<T extends string> = T extends string
  ? T extends '/'
    ? 'index'
    : ValidateAuthRul<T> extends true
      ? 'auth-rul'
      : ValidateChats<T> extends true
        ? 'chats'
        : ValidateEmployees<T> extends true
          ? 'employees-index'
          : ValidateMyAuction<T> extends true
            ? 'my-auction'
            : ValidateMyProducts<T> extends true
              ? 'my-products-index'
              : ValidateMyProductsAddProductsRealTimeStoreId<T> extends true
                ? 'my-products-add_products-realTime-storeId'
                : ValidateMyProductsAddProductsVirtual<T> extends true
                  ? 'my-products-add_products-virtual'
                  : ValidateMyProductsAddStore<T> extends true
                    ? 'my-products-add_store'
                    : ValidateMyProductsEditProductRealTimeProductId<T> extends true
                      ? 'my-products-edit_product-realTime-productId'
                      : ValidateMyProductsEditProductVirtualProductId<T> extends true
                        ? 'my-products-edit_product-virtual-productId'
                        : ValidateMyProductsOrdersAndPaymentPageIndexStoreIdDeliveryStoreId<T> extends true
                          ? 'my-products-orders-and-payment-page-index-storeId-delivery-storeId'
                          : ValidateMyProductsOrdersAndPaymentPageIndexStoreIdSelfStoreId<T> extends true
                            ? 'my-products-orders-and-payment-page-index-storeId-self-storeId'
                            : ValidateMyProductsEditStoreStoreId<T> extends true
                              ? 'my-products-edit_store-storeId'
                              : ValidateMyProductsRealTimeStoreId<T> extends true
                                ? 'my-products-index-realTime-storeId'
                                : ValidateMyProductsVirtual<T> extends true
                                  ? 'my-products-index-virtual'
                                  : ValidateMyProductsOrderPerStoreStoreid<T> extends true
                                    ? 'my-products-order_per_store-storeid'
                                    : ValidateMyProductsOrdersAndPayment<T> extends true
                                      ? 'my-products-orders-and-payment'
                                      : ValidateMyProductsSpecialDiscount<T> extends true
                                        ? 'my-products-special-discount'
                                        : ValidateMyServices<T> extends true
                                          ? 'my-services-index'
                                          : ValidateMyServicesAddRealtime<T> extends true
                                            ? 'my-services-add-realtime'
                                            : ValidateMyServicesAddVirtual<T> extends true
                                              ? 'my-services-add-virtual'
                                              : ValidateMyServicesEditRealtimeServiceId<T> extends true
                                                ? 'my-services-edit-realtime-service_id'
                                                : ValidateMyServicesEditVirtualServiceId<T> extends true
                                                  ? 'my-services-edit-virtual-service_id'
                                                  : ValidateMyServicesVirtual<T> extends true
                                                    ? 'my-services-index-virtual'
                                                    : ValidateMyServicesOrdersAndPayment<T> extends true
                                                      ? 'my-services-orders-and-payment'
                                                      : ValidateReview<T> extends true
                                                        ? 'review'
                                                        : ValidateSettings<T> extends true
                                                          ? 'settings'
                                                          : ValidateStoreEmployeeAccount<T> extends true
                                                            ? 'store-employee-account'
                                                            : ValidateStoreEmployee<T> extends true
                                                              ? 'store-employee'
                                                              : ValidateStoreEmployeeChats<T> extends true
                                                                ? 'store-employee-chats'
                                                                : ValidateStoreEmployeeOrderPageIndexStoreIdDeliveryStoreId<T> extends true
                                                                  ? 'store-employee-order-page-index-storeId-delivery-storeId'
                                                                  : ValidateStoreEmployeeOrderPageIndexStoreIdSelfStoreId<T> extends true
                                                                    ? 'store-employee-order-page-index-storeId-self-storeId'
                                                                    : ValidateStoreEmployeeAddProductStoreId<T> extends true
                                                                      ? 'store-employee-add-product-storeId'
                                                                      : ValidateStoreEmployeeDiscount<T> extends true
                                                                        ? 'store-employee-discount'
                                                                        : ValidateStoreEmployeeEditProductProductId<T> extends true
                                                                          ? 'store-employee-edit-product-productId'
                                                                          : ValidateStoreEmployeeProductsStoreId<T> extends true
                                                                            ? 'store-employee-products-storeId'
                                                                            : ValidateStoreEmployeeStore<T> extends true
                                                                              ? 'store-employee-store'
                                                                              : never
  : never;

export type TypedPathParameter<T extends string> = ValidatePath<T> | RoutePathSchema;
