// @ts-nocheck
// eslint-disable
// ---------------------------------------------------
// 🚗🚦 Generated by nuxt-typed-router. Do not modify !
// ---------------------------------------------------

/**
 * Exhaustive list of all the available route names in the app
 * */
export type RoutesNamesList =
  | 'auth-rul'
  | 'chats'
  | 'employees-index'
  | 'index'
  | 'my-auction'
  | 'my-products-add_products-realTime-storeId'
  | 'my-products-add_products-virtual'
  | 'my-products-add_store'
  | 'my-products-edit_product-realTime-productId'
  | 'my-products-edit_product-virtual-productId'
  | 'my-products-edit_store-storeId'
  | 'my-products-index'
  | 'my-products-index-realTime-storeId'
  | 'my-products-index-virtual'
  | 'my-products-order_per_store-storeid'
  | 'my-products-orders-and-payment-page-index-storeId-delivery-storeId'
  | 'my-products-orders-and-payment-page-index-storeId-self-storeId'
  | 'my-products-orders-and-payment'
  | 'my-products-special-discount'
  | 'my-services-add-realtime'
  | 'my-services-add-virtual'
  | 'my-services-edit-realtime-service_id'
  | 'my-services-edit-virtual-service_id'
  | 'my-services-index'
  | 'my-services-index-virtual'
  | 'my-services-orders-and-payment'
  | 'review'
  | 'settings'
  | 'store-employee-account'
  | 'store-employee-add-product-storeId'
  | 'store-employee-chats'
  | 'store-employee-discount'
  | 'store-employee-edit-product-productId'
  | 'store-employee'
  | 'store-employee-order-page-index-storeId-delivery-storeId'
  | 'store-employee-order-page-index-storeId-self-storeId'
  | 'store-employee-products-storeId'
  | 'store-employee-store';

/**
 * Routes params are only required for the exact targeted route name,
 * vue-router behaviour allow to navigate between children routes without the need to provide all the params every time.
 * So we can't enforce params when navigating between routes, only a `[xxx].vue` page will have required params in the type definition
 *
 * */
export type RoutesParamsRecord = {
  'auth-rul': never;
  chats: never;
  'employees-index': never;
  index: never;
  'my-auction': never;
  'my-products-add_products-realTime-storeId': {
    storeId: string | number;
  };
  'my-products-add_products-virtual': never;
  'my-products-add_store': never;
  'my-products-edit_product-realTime-productId': {
    productId: string | number;
  };
  'my-products-edit_product-virtual-productId': {
    productId: string | number;
  };
  'my-products-edit_store-storeId': {
    storeId: string | number;
  };
  'my-products-index': never;
  'my-products-index-realTime-storeId': {
    storeId: string | number;
  };
  'my-products-index-virtual': never;
  'my-products-order_per_store-storeid': {
    storeid: string | number;
  };
  'my-products-orders-and-payment-page-index-storeId-delivery-storeId': {
    storeId?: string | number;
    storeId: string | number;
  };
  'my-products-orders-and-payment-page-index-storeId-self-storeId': {
    storeId?: string | number;
    storeId: string | number;
  };
  'my-products-orders-and-payment': never;
  'my-products-special-discount': never;
  'my-services-add-realtime': never;
  'my-services-add-virtual': never;
  'my-services-edit-realtime-service_id': {
    service_id: string | number;
  };
  'my-services-edit-virtual-service_id': {
    service_id: string | number;
  };
  'my-services-index': never;
  'my-services-index-virtual': never;
  'my-services-orders-and-payment': never;
  review: never;
  settings: never;
  'store-employee-account': never;
  'store-employee-add-product-storeId': {
    storeId: string | number;
  };
  'store-employee-chats': never;
  'store-employee-discount': never;
  'store-employee-edit-product-productId': {
    productId: string | number;
  };
  'store-employee': never;
  'store-employee-order-page-index-storeId-delivery-storeId': {
    storeId?: string | number;
    storeId: string | number;
  };
  'store-employee-order-page-index-storeId-self-storeId': {
    storeId?: string | number;
    storeId: string | number;
  };
  'store-employee-products-storeId': {
    storeId: string | number;
  };
  'store-employee-store': never;
};

/**
 * Record resolved used for resolved routes
 *
 * */
export type RoutesParamsRecordResolved = {
  'auth-rul': never;
  chats: never;
  'employees-index': never;
  index: never;
  'my-auction': never;
  'my-products-add_products-realTime-storeId': {
    storeId: string;
  };
  'my-products-add_products-virtual': never;
  'my-products-add_store': never;
  'my-products-edit_product-realTime-productId': {
    productId: string;
  };
  'my-products-edit_product-virtual-productId': {
    productId: string;
  };
  'my-products-edit_store-storeId': {
    storeId: string;
  };
  'my-products-index': never;
  'my-products-index-realTime-storeId': {
    storeId: string;
  };
  'my-products-index-virtual': never;
  'my-products-order_per_store-storeid': {
    storeid: string;
  };
  'my-products-orders-and-payment-page-index-storeId-delivery-storeId': {
    storeId: string;
    storeId: string;
  };
  'my-products-orders-and-payment-page-index-storeId-self-storeId': {
    storeId: string;
    storeId: string;
  };
  'my-products-orders-and-payment': never;
  'my-products-special-discount': never;
  'my-services-add-realtime': never;
  'my-services-add-virtual': never;
  'my-services-edit-realtime-service_id': {
    service_id: string;
  };
  'my-services-edit-virtual-service_id': {
    service_id: string;
  };
  'my-services-index': never;
  'my-services-index-virtual': never;
  'my-services-orders-and-payment': never;
  review: never;
  settings: never;
  'store-employee-account': never;
  'store-employee-add-product-storeId': {
    storeId: string;
  };
  'store-employee-chats': never;
  'store-employee-discount': never;
  'store-employee-edit-product-productId': {
    productId: string;
  };
  'store-employee': never;
  'store-employee-order-page-index-storeId-delivery-storeId': {
    storeId: string;
    storeId: string;
  };
  'store-employee-order-page-index-storeId-self-storeId': {
    storeId: string;
    storeId: string;
  };
  'store-employee-products-storeId': {
    storeId: string;
  };
  'store-employee-store': never;
};

/**
 * Discriminated union that will allow to infer params based on route name
 * It's used for programmatic navigation like router.push or <NuxtLink/>
 * */
export type RoutesNamedLocations =
  | { name: 'auth-rul' }
  | { name: 'chats' }
  | { name: 'employees-index' }
  | { name: 'index' }
  | { name: 'my-auction' }
  | {
      name: 'my-products-add_products-realTime-storeId';
      params: {
        storeId: string | number;
      };
    }
  | { name: 'my-products-add_products-virtual' }
  | { name: 'my-products-add_store' }
  | {
      name: 'my-products-edit_product-realTime-productId';
      params: {
        productId: string | number;
      };
    }
  | {
      name: 'my-products-edit_product-virtual-productId';
      params: {
        productId: string | number;
      };
    }
  | {
      name: 'my-products-edit_store-storeId';
      params: {
        storeId: string | number;
      };
    }
  | { name: 'my-products-index' }
  | {
      name: 'my-products-index-realTime-storeId';
      params: {
        storeId: string | number;
      };
    }
  | { name: 'my-products-index-virtual' }
  | {
      name: 'my-products-order_per_store-storeid';
      params: {
        storeid: string | number;
      };
    }
  | {
      name: 'my-products-orders-and-payment-page-index-storeId-delivery-storeId';
      params: {
        storeId?: string | number;
        storeId: string | number;
      };
    }
  | {
      name: 'my-products-orders-and-payment-page-index-storeId-self-storeId';
      params: {
        storeId?: string | number;
        storeId: string | number;
      };
    }
  | { name: 'my-products-orders-and-payment' }
  | { name: 'my-products-special-discount' }
  | { name: 'my-services-add-realtime' }
  | { name: 'my-services-add-virtual' }
  | {
      name: 'my-services-edit-realtime-service_id';
      params: {
        service_id: string | number;
      };
    }
  | {
      name: 'my-services-edit-virtual-service_id';
      params: {
        service_id: string | number;
      };
    }
  | { name: 'my-services-index' }
  | { name: 'my-services-index-virtual' }
  | { name: 'my-services-orders-and-payment' }
  | { name: 'review' }
  | { name: 'settings' }
  | { name: 'store-employee-account' }
  | {
      name: 'store-employee-add-product-storeId';
      params: {
        storeId: string | number;
      };
    }
  | { name: 'store-employee-chats' }
  | { name: 'store-employee-discount' }
  | {
      name: 'store-employee-edit-product-productId';
      params: {
        productId: string | number;
      };
    }
  | { name: 'store-employee' }
  | {
      name: 'store-employee-order-page-index-storeId-delivery-storeId';
      params: {
        storeId?: string | number;
        storeId: string | number;
      };
    }
  | {
      name: 'store-employee-order-page-index-storeId-self-storeId';
      params: {
        storeId?: string | number;
        storeId: string | number;
      };
    }
  | {
      name: 'store-employee-products-storeId';
      params: {
        storeId: string | number;
      };
    }
  | { name: 'store-employee-store' };

/**
 * Type returned by a resolved Route that will allow to type guard the route name.
 * By default the params are unknown
 * */
export type RoutesNamedLocationsResolved = {
  name: RoutesNamesList;
  params: unknown;
} & (
  | { name: 'auth-rul' }
  | { name: 'chats' }
  | { name: 'employees-index' }
  | { name: 'index' }
  | { name: 'my-auction' }
  | {
      name: 'my-products-add_products-realTime-storeId';
      params: {
        storeId: string;
      };
    }
  | { name: 'my-products-add_products-virtual' }
  | { name: 'my-products-add_store' }
  | {
      name: 'my-products-edit_product-realTime-productId';
      params: {
        productId: string;
      };
    }
  | {
      name: 'my-products-edit_product-virtual-productId';
      params: {
        productId: string;
      };
    }
  | {
      name: 'my-products-edit_store-storeId';
      params: {
        storeId: string;
      };
    }
  | { name: 'my-products-index' }
  | {
      name: 'my-products-index-realTime-storeId';
      params: {
        storeId: string;
      };
    }
  | { name: 'my-products-index-virtual' }
  | {
      name: 'my-products-order_per_store-storeid';
      params: {
        storeid: string;
      };
    }
  | {
      name: 'my-products-orders-and-payment-page-index-storeId-delivery-storeId';
      params: {
        storeId: string;
        storeId: string;
      };
    }
  | {
      name: 'my-products-orders-and-payment-page-index-storeId-self-storeId';
      params: {
        storeId: string;
        storeId: string;
      };
    }
  | { name: 'my-products-orders-and-payment' }
  | { name: 'my-products-special-discount' }
  | { name: 'my-services-add-realtime' }
  | { name: 'my-services-add-virtual' }
  | {
      name: 'my-services-edit-realtime-service_id';
      params: {
        service_id: string;
      };
    }
  | {
      name: 'my-services-edit-virtual-service_id';
      params: {
        service_id: string;
      };
    }
  | { name: 'my-services-index' }
  | { name: 'my-services-index-virtual' }
  | { name: 'my-services-orders-and-payment' }
  | { name: 'review' }
  | { name: 'settings' }
  | { name: 'store-employee-account' }
  | {
      name: 'store-employee-add-product-storeId';
      params: {
        storeId: string;
      };
    }
  | { name: 'store-employee-chats' }
  | { name: 'store-employee-discount' }
  | {
      name: 'store-employee-edit-product-productId';
      params: {
        productId: string;
      };
    }
  | { name: 'store-employee' }
  | {
      name: 'store-employee-order-page-index-storeId-delivery-storeId';
      params: {
        storeId: string;
        storeId: string;
      };
    }
  | {
      name: 'store-employee-order-page-index-storeId-self-storeId';
      params: {
        storeId: string;
        storeId: string;
      };
    }
  | {
      name: 'store-employee-products-storeId';
      params: {
        storeId: string;
      };
    }
  | { name: 'store-employee-store' }
);

export type RoutesNamesListRecord = {
  authRul: 'auth-rul';
  chats: { index: 'chats' };
  employees: { index: 'employees-index' };
  index: 'index';
  myAuction: 'my-auction';
  myProductsAddProductsRealTimeStoreId: 'my-products-add_products-realTime-storeId';
  myProductsAddProductsVirtual: 'my-products-add_products-virtual';
  myProductsAddStore: 'my-products-add_store';
  myProductsEditProductRealTimeProductId: 'my-products-edit_product-realTime-productId';
  myProductsEditProductVirtualProductId: 'my-products-edit_product-virtual-productId';
  myProductsEditStoreStoreId: 'my-products-edit_store-storeId';
  myProducts: {
    index: 'my-products-index';
    productsIndexRealTimeStoreId: 'my-products-index-realTime-storeId';
    productsIndexVirtual: 'my-products-index-virtual';
  };
  myProductsOrderPerStoreStoreid: 'my-products-order_per_store-storeid';
  myProductsOrdersAndPaymentPageIndexStoreId: {
    productsOrdersAndPaymentPageIndexStoreIdDeliveryStoreId: 'my-products-orders-and-payment-page-index-storeId-delivery-storeId';
    productsOrdersAndPaymentPageIndexStoreIdSelfStoreId: 'my-products-orders-and-payment-page-index-storeId-self-storeId';
  };
  myProductsOrdersAndPayment: 'my-products-orders-and-payment';
  myProductsSpecialDiscount: 'my-products-special-discount';
  myServicesAddRealtime: 'my-services-add-realtime';
  myServicesAddVirtual: 'my-services-add-virtual';
  myServicesEditRealtimeServiceId: 'my-services-edit-realtime-service_id';
  myServicesEditVirtualServiceId: 'my-services-edit-virtual-service_id';
  myServices: { index: 'my-services-index'; servicesIndexVirtual: 'my-services-index-virtual' };
  myServicesOrdersAndPayment: 'my-services-orders-and-payment';
  review: 'review';
  settings: 'settings';
  storeEmployeeAccount: 'store-employee-account';
  storeEmployeeAddProductStoreId: 'store-employee-add-product-storeId';
  storeEmployeeChats: { index: 'store-employee-chats' };
  storeEmployeeDiscount: 'store-employee-discount';
  storeEmployeeEditProductProductId: 'store-employee-edit-product-productId';
  storeEmployee: 'store-employee';
  storeEmployeeOrderPageIndexStoreId: {
    employeeOrderPageIndexStoreIdDeliveryStoreId: 'store-employee-order-page-index-storeId-delivery-storeId';
    employeeOrderPageIndexStoreIdSelfStoreId: 'store-employee-order-page-index-storeId-self-storeId';
  };
  storeEmployeeProductsStoreId: 'store-employee-products-storeId';
  storeEmployeeStore: 'store-employee-store';
};

export const routesNames = {
  authRul: 'auth-rul' as const,
  chats: { index: 'chats' as const },
  employees: { index: 'employees-index' as const },
  index: 'index' as const,
  myAuction: 'my-auction' as const,
  myProductsAddProductsRealTimeStoreId: 'my-products-add_products-realTime-storeId' as const,
  myProductsAddProductsVirtual: 'my-products-add_products-virtual' as const,
  myProductsAddStore: 'my-products-add_store' as const,
  myProductsEditProductRealTimeProductId: 'my-products-edit_product-realTime-productId' as const,
  myProductsEditProductVirtualProductId: 'my-products-edit_product-virtual-productId' as const,
  myProductsEditStoreStoreId: 'my-products-edit_store-storeId' as const,
  myProducts: {
    index: 'my-products-index' as const,
    productsIndexRealTimeStoreId: 'my-products-index-realTime-storeId' as const,
    productsIndexVirtual: 'my-products-index-virtual' as const,
  },
  myProductsOrderPerStoreStoreid: 'my-products-order_per_store-storeid' as const,
  myProductsOrdersAndPaymentPageIndexStoreId: {
    productsOrdersAndPaymentPageIndexStoreIdDeliveryStoreId:
      'my-products-orders-and-payment-page-index-storeId-delivery-storeId' as const,
    productsOrdersAndPaymentPageIndexStoreIdSelfStoreId:
      'my-products-orders-and-payment-page-index-storeId-self-storeId' as const,
  },
  myProductsOrdersAndPayment: 'my-products-orders-and-payment' as const,
  myProductsSpecialDiscount: 'my-products-special-discount' as const,
  myServicesAddRealtime: 'my-services-add-realtime' as const,
  myServicesAddVirtual: 'my-services-add-virtual' as const,
  myServicesEditRealtimeServiceId: 'my-services-edit-realtime-service_id' as const,
  myServicesEditVirtualServiceId: 'my-services-edit-virtual-service_id' as const,
  myServices: {
    index: 'my-services-index' as const,
    servicesIndexVirtual: 'my-services-index-virtual' as const,
  },
  myServicesOrdersAndPayment: 'my-services-orders-and-payment' as const,
  review: 'review' as const,
  settings: 'settings' as const,
  storeEmployeeAccount: 'store-employee-account' as const,
  storeEmployeeAddProductStoreId: 'store-employee-add-product-storeId' as const,
  storeEmployeeChats: { index: 'store-employee-chats' as const },
  storeEmployeeDiscount: 'store-employee-discount' as const,
  storeEmployeeEditProductProductId: 'store-employee-edit-product-productId' as const,
  storeEmployee: 'store-employee' as const,
  storeEmployeeOrderPageIndexStoreId: {
    employeeOrderPageIndexStoreIdDeliveryStoreId:
      'store-employee-order-page-index-storeId-delivery-storeId' as const,
    employeeOrderPageIndexStoreIdSelfStoreId:
      'store-employee-order-page-index-storeId-self-storeId' as const,
  },
  storeEmployeeProductsStoreId: 'store-employee-products-storeId' as const,
  storeEmployeeStore: 'store-employee-store' as const,
};
