# query ($user_id: String!) {
#   message(
#     where: {
#       _or: [
#         { receiver_id: { _eq: $user_id } }
#         { sender_id: { _eq: $user_id } }
#       ]
#     }
#     order_by: { created_at: asc }
#   ) {
#     message
#     id
#     sender_id
#     created_at

#     receiver_id
#     seen
#     userBySenderId {
#       id
#       first_name
#       last_name
#     }
#     user {
#       id
#       first_name
#       last_name
#     }
#   }
# }

query ($where: users_bool_exp, $messageWhere: message_bool_exp) {
  users(where: $where) {
    id
    email
    first_name
    last_name
    sender:messages(limit: 1, order_by: { created_at: desc }, where: $messageWhere) {
      id
      message
      receiver_id
      sender_id
      created_at
    }
    receiver:messagesBySenderId(
      limit: 1
      order_by: { created_at: desc }
      where: $messageWhere
    ) {
      id
      message
      sender_id
      receiver_id
      created_at
    }
  }
}
