query fetch_virtual_service_category {
  virtual_service_categories: service_virtual_service_category {
    id
    logo
    primary: original_language {
      id
      translation_contents {
        language_type
        name
      }
    }
  }
}
